version: '3.7'

services:
  postgres:
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: 'ama'
      POSTGRES_PASSWORD: 'admin'
      POSTGRES_DB: 'ama'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    ports:
      - 127.0.0.1:${DATABASE_PORT}:5432
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ama']
      interval: 10s
      timeout: 5s

  bot:
    image: chatsift/ama
    build:
      context: ./
      dockerfile: ./Dockerfile
    env_file:
      - ./.env
    environment:
      DATABASE_URL: 'postgresql://ama:admin@postgres:5432/ama'
    restart: unless-stopped
    volumes:
      - ./logs:/usr/ama/logs
    depends_on:
      - postgres
    command: ['node', '--enable-source-maps', '--no-warnings', './packages/bot/dist/index.js']

volumes:
  postgres-data:
    name: 'ama-postgres-data'
