version: "3.7"

services:
  postgres:
    expose:
      - "5432"

  redis:
    expose:
      - "6379"

  prometheus:
    expose:
      - "9000"

  gateway:
    environment:
      CORDIS_DEBUG: "true"

  handler:
    environment:
      NODE_ENV: "dev"
      TEST_GUILD_ID: "209566902522085376"
    ports:
      - "127.0.0.1:9229:9229"
    expose:
      - "9229"
    command: ["node", "--enable-source-maps", "--inspect=0.0.0.0", "services/handler/dist/index.js"]

  grafana:
    environment:
      GF_SECURITY_ADMIN_USER: "admin"
      GF_SECURITY_ADMIN_PASSWORD: "admin"
    expose:
      - "5000"
