version: "3.7"

services:
  postgres:
    build:
      context: ./docker/postgresql
      dockerfile: ./Dockerfile
    environment:
      POSTGRES_USER: "ama"
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DB: "ama"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ama"]
      interval: 10s
      timeout: 5s

  handler:
    build:
      context: ./
      dockerfile: ./docker/handler/Dockerfile
    restart: unless-stopped
    environment:
      REDIS_URL: "redis://redis:6379"
      DB_URL: "postgres://ama:admin@postgres:5432/ama?sslmode=disable"
    ports:
      - "127.0.0.1:4000:4000"
    depends_on:
      - postgres

volumes:
  postgres-data:
    name: "ama-postgres-data"
